version: '3.5'
services:
  edgedb:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_ADMIN_UI: enabled
      EDGEDB_SERVER_BIND_ADDRESS: 0.0.0.0
    volumes:
      - ".:/harmonic"
    ports:
      - "10701:10700"
  data_services:
    links:
      - edgedb:edgedb
    volumes:
      - "./:/harmonic"
    ports:
      - "5001:5001"
    environment:
      API_PORT: 5001
      EDGEDB_PORT: 10700
      EDGEDB_HOST: edgedb
      INGESTION_PIPE: ingestion
      EDGEDB_CLIENT_SECURITY: insecure_dev_mode
    build:
      context: .
      dockerfile: Dockerfile
      
